Document: gitsh
Title: Debian gitsh Manual
Author: <insert document author here>
Abstract: This manual describes what gitsh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gitsh/gitsh.sgml.gz

Format: postscript
Files: /usr/share/doc/gitsh/gitsh.ps.gz

Format: text
Files: /usr/share/doc/gitsh/gitsh.text.gz

Format: HTML
Index: /usr/share/doc/gitsh/html/index.html
Files: /usr/share/doc/gitsh/html/*.html
